//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FilmClientWinForms.FilmReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FilmServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FilmService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AdaugaFilmOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificaFilmOperationCompleted;
        
        private System.Threading.SendOrPostCallback StergeFilmOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiseazaFilmeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FiltreazaDupaGenOperationCompleted;
        
        private System.Threading.SendOrPostCallback CautaDupaTitluOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FilmService() {
            this.Url = global::FilmClientWinForms.Properties.Settings.Default.FilmClientWinForms_FilmReference_FilmService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AdaugaFilmCompletedEventHandler AdaugaFilmCompleted;
        
        /// <remarks/>
        public event ModificaFilmCompletedEventHandler ModificaFilmCompleted;
        
        /// <remarks/>
        public event StergeFilmCompletedEventHandler StergeFilmCompleted;
        
        /// <remarks/>
        public event AfiseazaFilmeCompletedEventHandler AfiseazaFilmeCompleted;
        
        /// <remarks/>
        public event FiltreazaDupaGenCompletedEventHandler FiltreazaDupaGenCompleted;
        
        /// <remarks/>
        public event CautaDupaTitluCompletedEventHandler CautaDupaTitluCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdaugaFilm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdaugaFilm(string titlu, string gen, int an, double rating) {
            object[] results = this.Invoke("AdaugaFilm", new object[] {
                        titlu,
                        gen,
                        an,
                        rating});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdaugaFilmAsync(string titlu, string gen, int an, double rating) {
            this.AdaugaFilmAsync(titlu, gen, an, rating, null);
        }
        
        /// <remarks/>
        public void AdaugaFilmAsync(string titlu, string gen, int an, double rating, object userState) {
            if ((this.AdaugaFilmOperationCompleted == null)) {
                this.AdaugaFilmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdaugaFilmOperationCompleted);
            }
            this.InvokeAsync("AdaugaFilm", new object[] {
                        titlu,
                        gen,
                        an,
                        rating}, this.AdaugaFilmOperationCompleted, userState);
        }
        
        private void OnAdaugaFilmOperationCompleted(object arg) {
            if ((this.AdaugaFilmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdaugaFilmCompleted(this, new AdaugaFilmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificaFilm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ModificaFilm(int id, string titlu, string gen, int an, double rating) {
            object[] results = this.Invoke("ModificaFilm", new object[] {
                        id,
                        titlu,
                        gen,
                        an,
                        rating});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModificaFilmAsync(int id, string titlu, string gen, int an, double rating) {
            this.ModificaFilmAsync(id, titlu, gen, an, rating, null);
        }
        
        /// <remarks/>
        public void ModificaFilmAsync(int id, string titlu, string gen, int an, double rating, object userState) {
            if ((this.ModificaFilmOperationCompleted == null)) {
                this.ModificaFilmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificaFilmOperationCompleted);
            }
            this.InvokeAsync("ModificaFilm", new object[] {
                        id,
                        titlu,
                        gen,
                        an,
                        rating}, this.ModificaFilmOperationCompleted, userState);
        }
        
        private void OnModificaFilmOperationCompleted(object arg) {
            if ((this.ModificaFilmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificaFilmCompleted(this, new ModificaFilmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StergeFilm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StergeFilm(int id) {
            object[] results = this.Invoke("StergeFilm", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StergeFilmAsync(int id) {
            this.StergeFilmAsync(id, null);
        }
        
        /// <remarks/>
        public void StergeFilmAsync(int id, object userState) {
            if ((this.StergeFilmOperationCompleted == null)) {
                this.StergeFilmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStergeFilmOperationCompleted);
            }
            this.InvokeAsync("StergeFilm", new object[] {
                        id}, this.StergeFilmOperationCompleted, userState);
        }
        
        private void OnStergeFilmOperationCompleted(object arg) {
            if ((this.StergeFilmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StergeFilmCompleted(this, new StergeFilmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiseazaFilme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Film[] AfiseazaFilme() {
            object[] results = this.Invoke("AfiseazaFilme", new object[0]);
            return ((Film[])(results[0]));
        }
        
        /// <remarks/>
        public void AfiseazaFilmeAsync() {
            this.AfiseazaFilmeAsync(null);
        }
        
        /// <remarks/>
        public void AfiseazaFilmeAsync(object userState) {
            if ((this.AfiseazaFilmeOperationCompleted == null)) {
                this.AfiseazaFilmeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiseazaFilmeOperationCompleted);
            }
            this.InvokeAsync("AfiseazaFilme", new object[0], this.AfiseazaFilmeOperationCompleted, userState);
        }
        
        private void OnAfiseazaFilmeOperationCompleted(object arg) {
            if ((this.AfiseazaFilmeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiseazaFilmeCompleted(this, new AfiseazaFilmeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FiltreazaDupaGen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Film[] FiltreazaDupaGen(string gen) {
            object[] results = this.Invoke("FiltreazaDupaGen", new object[] {
                        gen});
            return ((Film[])(results[0]));
        }
        
        /// <remarks/>
        public void FiltreazaDupaGenAsync(string gen) {
            this.FiltreazaDupaGenAsync(gen, null);
        }
        
        /// <remarks/>
        public void FiltreazaDupaGenAsync(string gen, object userState) {
            if ((this.FiltreazaDupaGenOperationCompleted == null)) {
                this.FiltreazaDupaGenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFiltreazaDupaGenOperationCompleted);
            }
            this.InvokeAsync("FiltreazaDupaGen", new object[] {
                        gen}, this.FiltreazaDupaGenOperationCompleted, userState);
        }
        
        private void OnFiltreazaDupaGenOperationCompleted(object arg) {
            if ((this.FiltreazaDupaGenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FiltreazaDupaGenCompleted(this, new FiltreazaDupaGenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CautaDupaTitlu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Film[] CautaDupaTitlu(string titlu) {
            object[] results = this.Invoke("CautaDupaTitlu", new object[] {
                        titlu});
            return ((Film[])(results[0]));
        }
        
        /// <remarks/>
        public void CautaDupaTitluAsync(string titlu) {
            this.CautaDupaTitluAsync(titlu, null);
        }
        
        /// <remarks/>
        public void CautaDupaTitluAsync(string titlu, object userState) {
            if ((this.CautaDupaTitluOperationCompleted == null)) {
                this.CautaDupaTitluOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCautaDupaTitluOperationCompleted);
            }
            this.InvokeAsync("CautaDupaTitlu", new object[] {
                        titlu}, this.CautaDupaTitluOperationCompleted, userState);
        }
        
        private void OnCautaDupaTitluOperationCompleted(object arg) {
            if ((this.CautaDupaTitluCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CautaDupaTitluCompleted(this, new CautaDupaTitluCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Film {
        
        private int idField;
        
        private string titluField;
        
        private string genField;
        
        private int anField;
        
        private double ratingField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Titlu {
            get {
                return this.titluField;
            }
            set {
                this.titluField = value;
            }
        }
        
        /// <remarks/>
        public string Gen {
            get {
                return this.genField;
            }
            set {
                this.genField = value;
            }
        }
        
        /// <remarks/>
        public int An {
            get {
                return this.anField;
            }
            set {
                this.anField = value;
            }
        }
        
        /// <remarks/>
        public double Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AdaugaFilmCompletedEventHandler(object sender, AdaugaFilmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdaugaFilmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdaugaFilmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ModificaFilmCompletedEventHandler(object sender, ModificaFilmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificaFilmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificaFilmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void StergeFilmCompletedEventHandler(object sender, StergeFilmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StergeFilmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StergeFilmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AfiseazaFilmeCompletedEventHandler(object sender, AfiseazaFilmeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiseazaFilmeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiseazaFilmeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Film[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Film[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FiltreazaDupaGenCompletedEventHandler(object sender, FiltreazaDupaGenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FiltreazaDupaGenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FiltreazaDupaGenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Film[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Film[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CautaDupaTitluCompletedEventHandler(object sender, CautaDupaTitluCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CautaDupaTitluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CautaDupaTitluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Film[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Film[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591