//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace StudentClientWinForms.StudentReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StudentServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StudentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AdaugaStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfisareStudentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback CautaStudentDupaIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StudentService() {
            this.Url = global::StudentClientWinForms.Properties.Settings.Default.StudentClientWinForms_StudentReference_StudentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AdaugaStudentCompletedEventHandler AdaugaStudentCompleted;
        
        /// <remarks/>
        public event AfisareStudentiCompletedEventHandler AfisareStudentiCompleted;
        
        /// <remarks/>
        public event CautaStudentDupaIDCompletedEventHandler CautaStudentDupaIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdaugaStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdaugaStudent(int id, string nume, string prenume, string specializare) {
            object[] results = this.Invoke("AdaugaStudent", new object[] {
                        id,
                        nume,
                        prenume,
                        specializare});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdaugaStudentAsync(int id, string nume, string prenume, string specializare) {
            this.AdaugaStudentAsync(id, nume, prenume, specializare, null);
        }
        
        /// <remarks/>
        public void AdaugaStudentAsync(int id, string nume, string prenume, string specializare, object userState) {
            if ((this.AdaugaStudentOperationCompleted == null)) {
                this.AdaugaStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdaugaStudentOperationCompleted);
            }
            this.InvokeAsync("AdaugaStudent", new object[] {
                        id,
                        nume,
                        prenume,
                        specializare}, this.AdaugaStudentOperationCompleted, userState);
        }
        
        private void OnAdaugaStudentOperationCompleted(object arg) {
            if ((this.AdaugaStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdaugaStudentCompleted(this, new AdaugaStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfisareStudenti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Student[] AfisareStudenti() {
            object[] results = this.Invoke("AfisareStudenti", new object[0]);
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void AfisareStudentiAsync() {
            this.AfisareStudentiAsync(null);
        }
        
        /// <remarks/>
        public void AfisareStudentiAsync(object userState) {
            if ((this.AfisareStudentiOperationCompleted == null)) {
                this.AfisareStudentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfisareStudentiOperationCompleted);
            }
            this.InvokeAsync("AfisareStudenti", new object[0], this.AfisareStudentiOperationCompleted, userState);
        }
        
        private void OnAfisareStudentiOperationCompleted(object arg) {
            if ((this.AfisareStudentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfisareStudentiCompleted(this, new AfisareStudentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CautaStudentDupaID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CautaStudentDupaID(int id) {
            object[] results = this.Invoke("CautaStudentDupaID", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CautaStudentDupaIDAsync(int id) {
            this.CautaStudentDupaIDAsync(id, null);
        }
        
        /// <remarks/>
        public void CautaStudentDupaIDAsync(int id, object userState) {
            if ((this.CautaStudentDupaIDOperationCompleted == null)) {
                this.CautaStudentDupaIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCautaStudentDupaIDOperationCompleted);
            }
            this.InvokeAsync("CautaStudentDupaID", new object[] {
                        id}, this.CautaStudentDupaIDOperationCompleted, userState);
        }
        
        private void OnCautaStudentDupaIDOperationCompleted(object arg) {
            if ((this.CautaStudentDupaIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CautaStudentDupaIDCompleted(this, new CautaStudentDupaIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Student {
        
        private int idField;
        
        private string numeField;
        
        private string prenumeField;
        
        private string specializareField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nume {
            get {
                return this.numeField;
            }
            set {
                this.numeField = value;
            }
        }
        
        /// <remarks/>
        public string Prenume {
            get {
                return this.prenumeField;
            }
            set {
                this.prenumeField = value;
            }
        }
        
        /// <remarks/>
        public string Specializare {
            get {
                return this.specializareField;
            }
            set {
                this.specializareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AdaugaStudentCompletedEventHandler(object sender, AdaugaStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdaugaStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdaugaStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AfisareStudentiCompletedEventHandler(object sender, AfisareStudentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfisareStudentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfisareStudentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CautaStudentDupaIDCompletedEventHandler(object sender, CautaStudentDupaIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CautaStudentDupaIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CautaStudentDupaIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591