//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UserClientWPF.UserReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidareEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidareParolaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InregistrareUtilizatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutentificareUtilizatorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserService() {
            this.Url = global::UserClientWPF.Properties.Settings.Default.UserClientWPF_UserReference_UserService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidareEmailCompletedEventHandler ValidareEmailCompleted;
        
        /// <remarks/>
        public event ValidareParolaCompletedEventHandler ValidareParolaCompleted;
        
        /// <remarks/>
        public event InregistrareUtilizatorCompletedEventHandler InregistrareUtilizatorCompleted;
        
        /// <remarks/>
        public event AutentificareUtilizatorCompletedEventHandler AutentificareUtilizatorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidareEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidareEmail(string email) {
            object[] results = this.Invoke("ValidareEmail", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidareEmailAsync(string email) {
            this.ValidareEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void ValidareEmailAsync(string email, object userState) {
            if ((this.ValidareEmailOperationCompleted == null)) {
                this.ValidareEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidareEmailOperationCompleted);
            }
            this.InvokeAsync("ValidareEmail", new object[] {
                        email}, this.ValidareEmailOperationCompleted, userState);
        }
        
        private void OnValidareEmailOperationCompleted(object arg) {
            if ((this.ValidareEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidareEmailCompleted(this, new ValidareEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidareParola", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidareParola(string parola) {
            object[] results = this.Invoke("ValidareParola", new object[] {
                        parola});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidareParolaAsync(string parola) {
            this.ValidareParolaAsync(parola, null);
        }
        
        /// <remarks/>
        public void ValidareParolaAsync(string parola, object userState) {
            if ((this.ValidareParolaOperationCompleted == null)) {
                this.ValidareParolaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidareParolaOperationCompleted);
            }
            this.InvokeAsync("ValidareParola", new object[] {
                        parola}, this.ValidareParolaOperationCompleted, userState);
        }
        
        private void OnValidareParolaOperationCompleted(object arg) {
            if ((this.ValidareParolaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidareParolaCompleted(this, new ValidareParolaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InregistrareUtilizator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InregistrareUtilizator(string email, string parola) {
            object[] results = this.Invoke("InregistrareUtilizator", new object[] {
                        email,
                        parola});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InregistrareUtilizatorAsync(string email, string parola) {
            this.InregistrareUtilizatorAsync(email, parola, null);
        }
        
        /// <remarks/>
        public void InregistrareUtilizatorAsync(string email, string parola, object userState) {
            if ((this.InregistrareUtilizatorOperationCompleted == null)) {
                this.InregistrareUtilizatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInregistrareUtilizatorOperationCompleted);
            }
            this.InvokeAsync("InregistrareUtilizator", new object[] {
                        email,
                        parola}, this.InregistrareUtilizatorOperationCompleted, userState);
        }
        
        private void OnInregistrareUtilizatorOperationCompleted(object arg) {
            if ((this.InregistrareUtilizatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InregistrareUtilizatorCompleted(this, new InregistrareUtilizatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutentificareUtilizator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutentificareUtilizator(string email, string parola) {
            object[] results = this.Invoke("AutentificareUtilizator", new object[] {
                        email,
                        parola});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutentificareUtilizatorAsync(string email, string parola) {
            this.AutentificareUtilizatorAsync(email, parola, null);
        }
        
        /// <remarks/>
        public void AutentificareUtilizatorAsync(string email, string parola, object userState) {
            if ((this.AutentificareUtilizatorOperationCompleted == null)) {
                this.AutentificareUtilizatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutentificareUtilizatorOperationCompleted);
            }
            this.InvokeAsync("AutentificareUtilizator", new object[] {
                        email,
                        parola}, this.AutentificareUtilizatorOperationCompleted, userState);
        }
        
        private void OnAutentificareUtilizatorOperationCompleted(object arg) {
            if ((this.AutentificareUtilizatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutentificareUtilizatorCompleted(this, new AutentificareUtilizatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ValidareEmailCompletedEventHandler(object sender, ValidareEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidareEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidareEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ValidareParolaCompletedEventHandler(object sender, ValidareParolaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidareParolaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidareParolaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void InregistrareUtilizatorCompletedEventHandler(object sender, InregistrareUtilizatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InregistrareUtilizatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InregistrareUtilizatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void AutentificareUtilizatorCompletedEventHandler(object sender, AutentificareUtilizatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutentificareUtilizatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutentificareUtilizatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591